name: Repository dispatch executes tests from Mockapic

on:
  repository_dispatch:
    types: ['trigger-from-event:build_and_test']

jobs:
  run_from_event:
    uses: ./.github/workflows/build_test_go_reusable.yml